#!/usr/bin/env bash

# Add color
eval "`dircolors -b \"$HOME/.dir_colors\"`"
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias less='less -R'
alias ls='ls --color=auto'

# Disable word wrap
alias nano='nano -w'

# Enable assertions
alias java='java -ea'

# Other
alias bdiff='vbindiff'
alias mtrr='mtr --report --report-cycles=1'
alias o='xdg-open'
alias quit='exit'
alias vi='vim'
alias wtf='apropos'
