#!/usr/bin/env bash

# Stop exectuting here if the shell is non-interactive
[ -z "$PS1" ] && return

# check the window size after each command
shopt -s checkwinsize

# Set command prompt
if [ "$UID" = "0" ] ; then
  PS1_COLOR=31
else
  PS1_COLOR=32
fi
if [ "$OSTYPE" = "linux-android" ]; then
  PS1='\[\033[01;34m\]\w\[\033[00m\]\$ '
else
  PS1='\[\033[01;'$PS1_COLOR'm\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

  # Set xterm title to user@host:dir
  case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
  *)
    ;;
  esac
fi

# Load alias definitions
if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# enable programmable completion features
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

## Configure custom locale

if [ -e "$HOME/.locale/en_ZZ.UTF-8" ]; then
  export LOCPATH=$HOME/.locale/
  export LANG=en_ZZ.UTF-8
fi

# A nicer default for coreutils
export TIME_STYLE=long-iso
