#!/usr/bin/env sh

# Run by Bourne-compatible login shells (bash, ash, dash, etc.)

umask 022

if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

# Deny messages 
if [ -x /usr/bin/mesg ] ; then
  mesg n || true
fi
