set modeline
set number
syntax on
set hlsearch

set enc=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf8,prc,utf-16,latin1

" Prefer LF line endings
set fileformats=unix,dos

" use "set eol" or "set noeol" to explicitly change the file's end-of-line format
set nofixendofline

" Show dos-only line endings on read-only files
" http://vim.wikia.com/wiki/Automatically_reload_files_with_mixed_line-endings_in_DOS_fileformat
autocmd BufReadPost * nested
  \ if !exists('b:reload_dos') && &ro && !&binary && &ff=='unix' && (0 < search('\r\%x00\?$', 'nc')) |
  \   let b:reload_dos = 1 |
  \   edit ++ff=dos |
  \   set ff=dos |
  \ endif

set statusline=
set statusline+=%f " Filename
set statusline+=%m " [+] or [-] when modified/unmodifiable
set statusline+=%r " [RO] when read-only
set statusline+=%h " [Help] when in help
set statusline+=%w " [Preview] when preview
set statusline+=\ [
set statusline+=%{&fenc!=''?&fenc:&enc} " File encoding
set statusline+=\| 
set statusline+=%{&ff} " Line endings
set statusline+=%{exists('b:reload_dos')?'*':''} " Mark re-interpreted
set statusline+=]
set statusline+=\ [
set statusline+=%Y " Filetype
set statusline+=]
set statusline+=%= " align right
set statusline+=%o " byte count at cursor
set statusline+=\ [%v,%l] " [virtual column v, line l]
set statusline+=(%p%%) " Percent (by line)

" Vim command prompt tab completion settings
set wildmode=list:longest
set wildmenu

set laststatus=2
set directory=.,$TEMP

" Disable backup/undo until cross-platform works better
"set backupdir=$TEMP
"set undodir=$TEMP
set nobackup
set noundofile

" Set indent behaviors
augroup indent_opts
  au BufEnter *
  \ syntax match Tab /\t/
  \ | hi Tab gui=underline guifg=blue ctermbg=blue
augroup END
set autoindent
set expandtab
set smarttab
set smartindent
set shiftwidth=2
set softtabstop=2
set tabstop=2

set tildeop

imap <f1> <esc>
map <f12> :set spell!<CR>
set nospell " No spell check by default
map <f11> :nohl<CR>
set mouse=a

if has("win32")
  let s:font = "Consolas:h<SIZE>:cANSI"
elseif has("gui_gtk2") || has("gui_gtk3")
  let s:font = "Fira\ Code\ Retina\ <SIZE>,Fira\ Code\ <SIZE>,Inconsolata\ <SIZE>,DejaVu\ Sans\ Mono\ <SIZE>,Monospace\ <SIZE>"
endif

function GetFontString(size)
  return substitute(s:font, "<SIZE>", a:size, "g")
endfunction

if has("gui_running")

  let &guifont = GetFontString("10")
  set guioptions=egm

  function SetFTColor(force)
    if a:force || !exists('b:colors_name')
      if &ft == "text" || &ft == "txt" || &ft == ""
        let b:colors_name = 'autumn'
      elseif &ft == "xml"
        let b:colors_name = 'ir_black'
      elseif &ft == "dosini"
        let b:colors_name = 'evening'
      elseif &ft == "dosbatch"
        let b:colors_name = 'solarized'
        let b:bg_type = 'dark'
      elseif &ft == "ps1"
        let b:colors_name = 'codeschool'
      elseif &ft == "netrw"
        let b:colors_name = 'desert'
      else
        let b:colors_name = 'solarized'
        let b:bg_type = 'dark'
      endif
    endif
    execute 'colorscheme' b:colors_name
    let g:colors_name = b:colors_name " workaround for themes like codeschool that sets to 'Code School 3'
    if exists('b:bg_type')
      let &background = b:bg_type
    endif
  endfunction

  " From http://stackoverflow.com/questions/6510481/colorscheme-change-when-filetype-changes
  augroup ft_colorscheme
    autocmd!
    autocmd FileType * call SetFTColor(1)
    autocmd BufEnter * call SetFTColor(0)
  augroup END
else
  colorscheme desert
endif

augroup ft_spellcheck
  autocmd!
  autocmd BufEnter * if &ft == "text" || &ft=="txt" || &ft == "" | set spell | else | set nospell
augroup END

" Print options
set printoptions=syntax:n,number:y
let &printfont = GetFontString("8")
