set nomodeline
set number
syntax on
set spell
set hlsearch

" Rely on AutoFenc.vim
set fileencodings=

" Show dos-only line endings on read-only files
" http://vim.wikia.com/wiki/Automatically_reload_files_with_mixed_line-endings_in_DOS_fileformat
autocmd BufReadPost * nested
  \ if !exists('b:reload_dos') && &ro && !&binary && &ff=='unix' && (0 < search('\r\%x00\?$', 'nc')) |
  \   let b:reload_dos = 1 |
  \   edit ++ff=dos |
  \   set ff=dos |
  \ endif

set statusline=%f%m%r%h%w\ [%{''.(&fenc!=''?&fenc:&enc).''}\|%{&ff}]\ [%Y]%=[%v,%l](%p%%)
set laststatus=2
set directory=.,$TEMP

" Disable backup/undo until cross-platform works better
"set backupdir=$TEMP
"set undodir=$TEMP
set nobackup
set noundofile

set autoindent
set expandtab
set shiftwidth=2
set tabstop=2
set smarttab
set smartindent
set tildeop

imap <f1> <esc>
map <f12> :set spell!<CR>
set nospell
map <f11> :nohl<CR>
set mouse=a

" Print options
set printoptions=syntax:n,number:y
set printfont=Consolas:h8:cANSI " Windows font only

colorscheme desert
if has("gui_running")

  set guifont=Consolas:h10:cANSI
  set guioptions=egm

  " From http://stackoverflow.com/questions/6510481/colorscheme-change-when-filetype-changes
  augroup ft_colorscheme
    au BufEnter *
    \ if !exists('b:colors_name') && !exists('b:bg_type')
        \ | if &ft == ""
            \ | let b:colors_name = 'autumn'
        \ | elseif &ft == "text"
            \ | let b:colors_name = 'autumn'
        \ | elseif &ft == "xml"
            \ | let b:colors_name = 'ir_black'
        \ | elseif &ft == "dosini"
            \ | let b:colors_name = 'evening'
        \ | elseif &ft == "dosbatch"
            \ | let b:colors_name = 'solarized'
            \ | let b:bg_type = 'dark'
        \ | elseif &ft == "ps1"
            \ | let b:colors_name = 'darkblue'
        \ | else
            \ | let b:colors_name = 'solarized'
            \ | let b:bg_type = 'dark'
        \ | endif
    \ | endif
    \ | exe 'colorscheme' b:colors_name
    \ | if exists('b:bg_type')
      \ | let &background = b:bg_type
  augroup END
endif
